/**
 * FEATURE_218 — the bundled KodaX self-manual registry.
 *
 * Drift discipline: dynamic facts (the provider list, the default provider)
 * are imported from live constants in `@kodax-ai/llm`, never copied as string
 * literals. A drift-guard test (registry.test.ts) asserts the providers topic
 * covers every provider in provider-capabilities.json.
 */

import { KODAX_PROVIDER_SNAPSHOTS, KODAX_DEFAULT_PROVIDER } from '@kodax-ai/llm';

import type { KodaXManualTopic, KodaXManualTopicId } from './types.js';

/** Live provider names — drift-proof source for the `providers` topic. */
const PROVIDER_NAMES: readonly string[] = Object.keys(KODAX_PROVIDER_SNAPSHOTS);
const PROVIDER_LIST = PROVIDER_NAMES.join(', ');

/** Canonical topic order (also the index ordering). */
export const MANUAL_TOPIC_IDS: readonly KodaXManualTopicId[] = [
  'overview',
  'license',
  'install',
  'quickstart',
  'providers',
  'custom-providers',
  'config',
  'permissions',
  'commands',
  'tools',
  'agents',
  'skills',
  'extensions',
  'mcp',
  'a2a',
  'repo-intelligence',
  'sessions',
  'memory',
  'doctor',
  'sdk',
  'troubleshooting',
];

/**
 * FEATURE_221 — the base topics that describe UNDERLYING KodaX MECHANISMS a
 * product built on the SDK inherits (provider/config/permission/tool/MCP/A2A/
 * skill/extension/session/repo-intel/SDK behavior). A white-label consumer who
 * fully replaces the manual (`selfManual.baseTopics = []`) can pass THIS list
 * instead to keep the agent able to accurately explain the mechanisms it stands
 * on — e.g. `selfManual.baseTopics = [...KODAX_UNDERLYING_CAPABILITY_TOPICS]`.
 *
 * Excluded from this set (KodaX-CLI-specific UX, not mechanisms a product
 * inherits): overview / license / install / quickstart / commands / agents / doctor /
 * troubleshooting. It is a recommended STARTING POINT — a consumer is free to
 * pass any explicit subset of `MANUAL_TOPIC_IDS`.
 */
export const KODAX_UNDERLYING_CAPABILITY_TOPICS: readonly KodaXManualTopicId[] = [
  'providers',
  'custom-providers',
  'config',
  'permissions',
  'tools',
  'skills',
  'extensions',
  'mcp',
  'a2a',
  'repo-intelligence',
  'sessions',
  'sdk',
];

const TOPICS: readonly KodaXManualTopic[] = [
  {
    id: 'overview',
    title: 'What KodaX is',
    aliases: ['about', 'what is kodax', 'intro', '介绍', '是什么', '概览'],
    summary: 'What KodaX is, what it is for, and how it differs from Claude Code / Codex CLI.',
    body: [
      'KodaX is a multi-provider AI coding CLI: an interactive REPL + SDK that plans,',
      `edits code, runs tools, and reviews its own work across ${PROVIDER_NAMES.length} LLM provider aliases.`,
      '',
      'Boundary: KodaX is its own product. It does NOT read .claude/settings.json (Claude',
      'Code) or config.toml (Codex CLI). KodaX is configured via ~/.kodax/config.json and',
      'KODAX_* env vars. When in doubt about a KodaX behavior, prefer this manual over',
      'general pretraining knowledge.',
    ].join('\n'),
    sources: [{ label: 'README', path: 'README.md' }],
    nextTopics: ['license', 'install', 'quickstart'],
  },
  {
    id: 'license',
    title: 'License & commercial-use boundary',
    aliases: [
      'licensing',
      'kai-fcl',
      'fair core',
      'commercial use',
      'non-commercial',
      '许可证',
      '许可协议',
      '商业使用',
      '商用',
    ],
    summary: 'KAI-FCL from v0.7.70, community use, commercial authorization, and historical Apache copies.',
    body: [
      'Official KodaX 0.7.70 and later distributions use the KodaX-AI Fair Core',
      'License (KAI-FCL) 1.0 or accompanying KodaX-AI customer terms.',
      'KAI-FCL is source-available / fair-core, not OSI open source.',
      '',
      'Community Use covers individual personal learning, individual non-commercial work,',
      'classroom instruction, non-production research, and contribution development/testing.',
      'Commercial or Managed Use is not granted by the community license. Company, team,',
      'institutional, government, production, intranet, managed-device, paid-service, hosted,',
      'or customer redistribution use requires a Customer Agreement with KodaX-AI and, where',
      'required, a valid License Entitlement.',
      '',
      'This change is not retroactive: historical tags, archives, binaries, npm packages, or',
      'other specific copies already distributed under Apache-2.0 keep that Apache-2.0 grant.',
      'Third-party components remain under their own licenses. The repository LICENSE file is',
      'the governing text; this topic is only a concise product summary.',
    ].join('\n'),
    sources: [
      { label: 'license', path: 'LICENSE' },
      { label: 'README license summary', path: 'README.md' },
    ],
    nextTopics: ['overview', 'install', 'sdk'],
  },
  {
    id: 'install',
    title: 'Install & start KodaX',
    aliases: ['setup', 'getting started', '安装', '启动', '怎么装'],
    summary: 'npm install, Node version, first launch, updating.',
    body: [
      'Install (Node >= 20):',
      '  npm install -g @kodax-ai/kodax',
      'Then run `kodax` in any project directory to start the interactive REPL.',
      '',
      'Native binaries (no Node needed) are published per release on GitHub Releases',
      '(darwin/linux/win, arm64/x64).',
      'Update: re-run the npm install, or download the new binary.',
    ].join('\n'),
    sources: [{ label: 'package', path: 'package.json' }],
    nextTopics: ['quickstart', 'providers', 'config'],
  },
  {
    id: 'quickstart',
    title: 'Quickstart workflow',
    aliases: ['workflow', 'first task', '快速开始', '上手', '怎么用'],
    summary: 'Open a project, give a task, review, run tests, continue a session.',
    body: [
      '1. `cd` into your repo and run `kodax`.',
      '2. Describe the task in plain language; KodaX plans, edits, and runs tools.',
      '3. Review proposed edits (permission mode controls auto-accept vs prompt).',
      '4. Ask it to run tests / build to verify.',
      '5. Continue later: `kodax -c` (continue last) or `kodax -r` (resume a picker).',
    ].join('\n'),
    sources: [{ label: 'commands', path: 'packages/repl/src/interactive/commands.ts' }],
    nextTopics: ['commands', 'permissions', 'sessions'],
  },
  {
    id: 'providers',
    title: 'Providers & models',
    aliases: ['provider', 'model', 'models', 'llm', '供应商', '模型', '提供商'],
    summary: 'Built-in providers, choosing a model, credential check, cross-provider fallback.',
    body: [
      `KodaX ships ${PROVIDER_NAMES.length} built-in provider aliases:`,
      `  ${PROVIDER_LIST}`,
      '',
      `Default provider: ${KODAX_DEFAULT_PROVIDER} (override with KODAX_PROVIDER env or`,
      '"provider" in ~/.kodax/config.json). Switch model live with the /model command.',
      '',
      'Public Kimi uses KIMI_API_KEY and defaults to `kimi-k2.7-code`; select',
      '`kimi-k2.7-code-highspeed`, `kimi-k2.6`, or `kimi-k2.5` explicitly. These routes',
      'have a 262,144-token context. K2.7 cannot disable thinking; K2.6 sends its required',
      'wire toggle when thinking is disabled. `kimi-code` is the separate Kimi For Coding',
      'subscription endpoint with KIMI_CODE_API_KEY. It keeps `kimi-for-coding` as default',
      'and offers `k3-256k` (Moderato), Kimi K3 as `k3` (1,048,576 tokens, Allegretto+),',
      'and `kimi-for-coding-highspeed`. Both K3 choices request upstream `k3`; reasoning',
      'uses `thinking.effort`, defaults to max, and supports explicit disable. Public Kimi',
      'and Kimi For Coding credentials are not interchangeable.',
      '',
      'Check a key works: `verifyCredential` (SDK) / a configured provider is validated via',
      'its verifyStrategy in provider-capabilities.json.',
      'Cross-provider fallback on hard errors: /fallback slash + KODAX_FALLBACK_PROVIDERS.',
      'Cheap/strong tiers for dispatched children: KODAX_FAST_* / KODAX_DEEP_*.',
    ].join('\n'),
    sources: [
      { label: 'provider capabilities', path: 'packages/llm/src/providers/provider-capabilities.json' },
    ],
    nextTopics: ['custom-providers', 'config', 'troubleshooting'],
  },
  {
    id: 'custom-providers',
    title: 'Custom providers',
    aliases: ['custom provider', 'baseurl', 'openai compatible', '自定义供应商', '自定义模型'],
    summary: 'Point KodaX at an OpenAI/Anthropic-compatible endpoint, incl. thinking config.',
    body: [
      'Add a `customProviders` entry in ~/.kodax/config.json for an OpenAI/Anthropic-',
      'compatible endpoint: specify the protocol, baseUrl, auth header(s), and model name(s).',
      'KodaX infers a verifyStrategy from the protocol; you can override it explicitly.',
      'Once added, the custom provider is selectable like any built-in one.',
      '',
      'Thinking / reasoning (set on the provider, or per-model in models[]):',
      '- supportsThinking: true is enough for most non-Claude models. With a bare',
      '  supportsThinking: true (no explicit reasoningPreset/reasoningProfile), openai-compat',
      '  stays passive — KodaX sends no thinking toggle and just surfaces the reasoning the',
      '  model emits; anthropic-compat sends thinking:{type:"enabled"}, which is what the',
      '  Anthropic-compatible endpoints of zhipu / kimi / minimax / deepseek expect. (An',
      '  explicit reasoningPreset/reasoningProfile can send a toggle on openai-compat too.)',
      '- openai-compat multi-turn caveat: some reasoning models (notably DeepSeek V4) reject a',
      '  later turn whose history drops the prior reasoning_content. If thinking shows on the',
      '  first turn but a follow-up errors, also set replayReasoningContent: true (per-provider',
      '  or per-model).',
      '- reasoning: { efforts: ["low","high"], default: "high" } adds a tunable effort level.',
      '  On openai-compat it sends reasoning_effort; on anthropic-compat it sends',
      '  thinking:{type:"enabled"} + reasoning_effort (the non-Claude dialect). Include "off"',
      '  in efforts to allow disabling thinking.',
      '- Pointing anthropic-compat at REAL Claude (4.6+)? Claude needs adaptive thinking, not',
      '  the enable toggle — set reasoningCapability: "native-adaptive" (or an explicit',
      '  reasoningProfile with effortStrategy "anthropic-output-effort").',
      '- reasoningCapability is the low-level override: native-toggle / native-budget /',
      '  native-effort / native-adaptive / none. It is ignored when supportsThinking is false.',
      'If a relay rejects the chosen thinking shape, KodaX retries the turn once without it, so',
      'it still completes (you just see no thinking) instead of erroring.',
    ].join('\n'),
    sources: [
      { label: 'config loader', path: 'packages/repl/src/common/utils.ts' },
      { label: 'custom provider reasoning', path: 'packages/llm/src/providers/custom-provider.ts' },
    ],
    nextTopics: ['providers', 'config'],
  },
  {
    id: 'config',
    title: 'Configuration',
    aliases: ['settings', 'config.json', 'env', '配置', '设置', '环境变量'],
    summary: 'Core config, split integration files, migration, and KODAX_* env precedence.',
    body: [
      'KodaX config is JSON + env vars — there is no YAML and no single loader entry.',
      'Core file: ~/.kodax/config.json. Common keys: provider, model, effort,',
      'planModeEffort, permissionMode, customProviders, repoIntelligenceMode,',
      'fallbackProviders, autoMode, verifierLog, stallLog, runtimeMode, and workflow.',
      '',
      'User integration declarations are versioned separately:',
      '- MCP:        ~/.kodax/integrations/mcp.json',
      '- A2A:        ~/.kodax/integrations/a2a.json',
      '- Extensions: ~/.kodax/integrations/extensions.json',
      'Run `kodax integrations migrate` for a dry run, then',
      '`kodax integrations migrate --apply` to create missing split files. Migration imports',
      'MCP and Extensions from config.json#mcpServers and config.json#extensions; A2A has no',
      'legacy source. It does not overwrite an existing destination. The first MCP/Extension mutation',
      'also stages readable legacy entries before applying the change. Review literal-secret warnings,',
      'then add `--cleanup-legacy` with `--apply` only after the destination validates; cleanup removes',
      'a legacy field only when its split destination exists. Initialize A2A with `a2a add` or an empty',
      'version-1 `{ "version": 1, "agents": {} }` document.',
      'Long-lived owners hot-reload',
      'valid changes and retain last-known-good state on failure; inbound A2A execution/store',
      'authority changes are reported as restart-required.',
      '',
      'Env mirrors / extras: KODAX_PROVIDER, KODAX_EFFORT, KODAX_FALLBACK_PROVIDERS, KODAX_FAST_*/KODAX_DEEP_*,',
      'KODAX_REPO_INTELLIGENCE. Env generally overrides file. Project vs user config:',
      'user config is ~/.kodax; project-scoped state lives under <repo>/.kodax/.',
    ].join('\n'),
    sources: [
      { label: 'config loader', path: 'packages/repl/src/common/utils.ts' },
      { label: 'integration config', path: 'packages/repl/src/common/integration-config.ts' },
      { label: 'canonical templates', path: 'config-templates/' },
      { label: 'permission config', path: 'packages/repl/src/common/permission-config.ts' },
    ],
    nextTopics: ['providers', 'permissions', 'mcp'],
  },
  {
    id: 'permissions',
    title: 'Permission modes',
    aliases: ['permission', 'approval', 'dangerous', '权限', '审批', '权限模式'],
    summary: 'File/command permission modes, approvals, read-only.',
    body: [
      'permissionMode controls when KodaX asks before file/command actions:',
      '- accept-edits: auto-apply edits, still gate risky commands.',
      '- plan: read-only planning, no mutations until you switch.',
      '- auto: data-driven classifier decides per action (KODAX_AUTO_MODE_*).',
      'Set via ~/.kodax/config.json "permissionMode" or the relevant slash command.',
      'Threat model: KodaX is a single-user CLI; workspace integrity is the user’s responsibility.',
    ].join('\n'),
    sources: [{ label: 'permission config', path: 'packages/repl/src/common/permission-config.ts' }],
    nextTopics: ['tools', 'commands', 'config'],
  },
  {
    id: 'commands',
    title: 'Commands (slash & CLI)',
    aliases: ['command', 'slash', 'cli', 'flags', '命令', '斜杠命令', '指令'],
    summary: 'REPL slash commands, CLI flags, and the doctor command.',
    body: [
      'All built-in REPL slash commands, grouped by purpose:',
      '- basics: /help, /status, /cost, /clear, /new, /exit, /copy, /paste.',
      '- model/runtime: /model, /provider, /thinking, /reasoning, /effort, /agent-mode,',
      '  /mode, /auto, /auto-engine, /auto-denials, /fallback.',
      '- context/session: /compact, /recover, /save, /load, /history, /sessions, /tree,',
      '  /fork, /rewind, /delete.',
      '- capabilities: /mcp, /repo-intel, /repointel (legacy redirect), /skill, /extensions,',
      '  /reload, /agents.',
      '- governance/work: /memory, /learn, /goal, /review, /workflow, /verifier-log, /stall-log.',
      'Use /help <topic> for this manual and /help for command usage.',
      'CLI: `kodax`, `kodax -c`, `kodax -r`, `kodax doctor [--ping]`, and',
      '`kodax sessions dedupe` (dry-run first). Integration/runtime commands include `kodax',
      'daemon`, `kodax integrations`, `kodax mcp`, `kodax extensions`, `kodax a2a`, and',
      '`kodax sandbox`. BUILTIN_COMMANDS is authoritative; a drift',
      'test requires every built-in slash command to remain named in this topic.',
    ].join('\n'),
    sources: [{ label: 'commands', path: 'packages/repl/src/interactive/commands.ts' }],
    nextTopics: ['doctor', 'sessions', 'permissions'],
  },
  {
    id: 'tools',
    title: 'Tools',
    aliases: ['tool', 'read', 'write', 'edit', 'bash', '工具'],
    summary: 'What KodaX tools do, when they read/write/run shell, completion verification.',
    body: [
      'KodaX agents use file tools (read, write, edit, multi_edit), search (grep, glob),',
      'and bash — gated by your permission mode. Write tools only mutate the workspace;',
      'read/search are side-effect free.',
      'On completion, an out-of-band Sidecar Verifier may re-check the result (a second',
      'opinion). This is automatic; you do not invoke it.',
    ].join('\n'),
    sources: [{ label: 'tools', path: 'packages/coding/src/tools/' }],
    nextTopics: ['agents', 'repo-intelligence', 'permissions'],
  },
  {
    id: 'agents',
    title: 'Custom agents',
    aliases: ['agent', 'subagent', 'specialist', '自定义agent', '智能体', '子代理'],
    summary: 'Author specialist agents in markdown; dispatch them as children.',
    body: [
      'Write a specialist agent as a markdown file with frontmatter (name, description,',
      'tools, model) + a body prompt. KodaX loads:',
      '  - user agents:    ~/.kodax/agents/*.md',
      '  - project agents: <repo>/.kodax/agents/*.md  (override user agents of the same name)',
      'The main Agent starts one through spawn_agent(agent_id="<name>").',
      'Difference from skills: an agent is a full sub-agent (own prompt/tools); a skill is',
      'reference knowledge injected into the current agent.',
    ].join('\n'),
    sources: [{ label: 'markdown loader', path: 'packages/coding/src/construction/markdown-loader.ts' }],
    nextTopics: ['skills', 'tools', 'sdk'],
  },
  {
    id: 'skills',
    title: 'Skills',
    aliases: ['skill', 'agent skills', '技能'],
    summary: 'What skills are, where they live, how they trigger, vs AGENTS.md.',
    body: [
      'Skills are reusable, zero-dependency knowledge/instruction bundles the agent can pull',
      'in on demand. Built-in skills ship inside the agent package',
      '(packages/agent/src/capabilities/skills/); user skills are discovered from disk.',
      'Trigger: the agent selects a relevant skill for the task. Versus AGENTS.md — AGENTS.md',
      'sets repo-wide rules always in context; a skill is task-specific and loaded when needed.',
      'Self-improvement: KodaX can propose skill refinements learned from your sessions; review',
      'them with /learn (pending / diff / approve / reject). Applying is snapshot-safe and never',
      'auto-runs — nothing changes a skill until you approve it.',
    ].join('\n'),
    sources: [{ label: 'skills', path: 'packages/agent/src/capabilities/skills/' }],
    nextTopics: ['agents', 'extensions', 'mcp'],
  },
  {
    id: 'extensions',
    title: 'Extensions',
    aliases: [
      'extension',
      'extensions',
      'plugin',
      'plugins',
      'runtime extension',
      'extension api',
      'write extension',
      'author extension',
      'extension.mjs',
      'kodax extension',
    ],
    summary: 'How to write, install, load, reload, and debug KodaX runtime extensions.',
    body: [
      'Extensions are trusted local code that extend the active KodaX runtime.',
      'Entry formats:',
      '  - package directory in ~/.kodax/extensions/<name>/ with extension.mjs/js/cjs/mts/ts/cts or index.*',
      '  - standalone module file (.js/.mjs/.cjs/.ts/.mts/.cts)',
      '',
      'Managed declarations live in ~/.kodax/integrations/extensions.json. Use `kodax',
      'extensions list|add|remove|reload`; repeated `--extension <path>` remains a launch-only',
      'override. Default discovery still scans ~/.kodax/extensions. Equivalent directory and',
      'entrypoint paths are deduped by resolved entrypoint.',
      'Until migration, config.json#extensions remains readable; the first managed mutation',
      'stages those legacy paths into the split file before changing it.',
      '',
      'Minimal extension:',
      '  export default function activate(api) {',
      '    api.registerTool({',
      '      name: "hello",',
      '      description: "Say hello",',
      '      input_schema: { type: "object", properties: {} },',
      '      sideEffect: "readonly",',
      '      handler: async () => "hello"',
      '    });',
      '  }',
      '',
      'Authoring surface: api.registerTool, registerCommand, registerSkillPath, registerAgent, registerCapabilityProvider, registerModelProvider, api.on(event), api.hook(hook), api.persistence, api.exec, and api.webhook. For TypeScript authors, import public types from @kodax-ai/coding/extensions.',
      '',
      'Operational commands: /extensions prints loaded modules, tools, commands, hooks,',
      'capabilities, defaults, and failures. /reload hot-reloads active modules. User-file',
      'reload is entry-transactional: an activation failure retains that entry\'s prior instance',
      'while independent additions/removals proceed. Extension slash commands appear in /help.',
      '',
      'Security boundary: extensions run as local trusted code in the KodaX process. Do not install untrusted extension modules; prefer MCP or a sidecar service for untrusted or heavyweight external integrations.',
    ].join('\n'),
    sources: [
      { label: 'extension api', path: 'packages/coding/src/extensions/types.ts' },
      { label: 'extension discovery', path: 'packages/coding/src/extensions/discovery.ts' },
      { label: 'extension runtime', path: 'packages/coding/src/extensions/runtime.ts' },
      { label: 'integration config', path: 'packages/repl/src/common/integration-config.ts' },
      { label: 'CLI extension loading', path: 'src/kodax_cli.ts' },
      { label: 'REPL extension commands', path: 'packages/repl/src/interactive/commands.ts' },
    ],
    nextTopics: ['config', 'skills', 'mcp'],
  },
  {
    id: 'mcp',
    title: 'MCP servers',
    aliases: ['mcp server', 'model context protocol', 'mcp配置'],
    summary: 'Configure, hot-reload, inspect, and troubleshoot MCP servers.',
    body: [
      'MCP declarations live in ~/.kodax/integrations/mcp.json (version 1; stdio or remote).',
      'Use `kodax mcp list|add|remove` to manage them and /mcp in the REPL to inspect live',
      'connection status. Legacy `mcpServers` in core config remains readable until explicitly',
      'migrated with `kodax integrations migrate --apply`.',
      '',
      'Long-lived owners hot-reload a valid candidate as one provider replacement and drain',
      'in-flight calls. Invalid edits keep the last-known-good provider. Credentials stay in',
      '${env:NAME} references. Common issues: wrong command/args, missing binary on PATH,',
      'missing credential env, or a server that needs interactive auth in a headless run.',
      '',
      '`mcp_search` returns exact capability ids from an untrusted catalog snapshot. Complete',
      'inventory/search pages are bounded by the physical result capacity and use revisioned',
      'cursors instead of silent truncation. A zero lexical match may return a lossless grouped',
      'exact-id inventory only when the entire filtered snapshot is cheaper than a normal page',
      'and fits capacity; otherwise it returns one concise catalog-language retry with no biased',
      'partial list. Stale/mixed snapshots and partial provider failure remain explicit.',
    ].join('\n'),
    sources: [
      { label: 'mcp', path: 'packages/agent/src/capabilities/mcp/' },
      { label: 'integration config', path: 'packages/repl/src/common/integration-config.ts' },
      { label: 'MCP runtime adapter', path: 'packages/repl/src/common/mcp-servers.ts' },
    ],
    nextTopics: ['config', 'a2a', 'tools'],
  },
  {
    id: 'a2a',
    title: 'A2A 1.0 integration',
    aliases: [
      'agent2agent',
      'agent card',
      'external agent',
      'a2a server',
      'a2a client',
      'a2a配置',
      '外部agent',
    ],
    summary: 'Configure, authenticate, activate, call, and serve A2A 1.0 Agents safely.',
    body: [
      'A2A declarations live in ~/.kodax/integrations/a2a.json (version 2). Legacy non-empty',
      'version 1 files stay readable but require `kodax a2a migrate` after every daemon using',
      'that config home is stopped. Use `kodax a2a add|list|test|call|enable|disable|remove`',
      'for outbound Agents, `kodax a2a expose` to configure an inbound profile, and',
      '`kodax a2a serve` to run the built-in server. `enabled` is desired state: disabling',
      'blocks new dispatch after owner reconciliation but does not cancel an admitted task.',
      'Configured outbound Agents register as `external:<name>` in embedded and user-daemon',
      'Runtimes. `serve` uses CLI/env/core-config/built-in provider precedence; an admitted',
      'Markdown Agent may pin its own provider/model, but remote input cannot override them.',
      '',
      'Outbound discovery accepts A2A 1.0 JSON-RPC only. The selected interface must stay on',
      'the same trusted origin as its Agent Card. One complete advertised security alternative',
      'must be satisfiable. Built-in outbound profiles support HTTP Bearer compatibility or',
      'OAuth 2.0 Client Credentials from an external Authorization Server; Card/RPC/token',
      'origins remain separate. `a2a test` plans security without obtaining an access token.',
      'Safe fetch also enforces TLS, DNS/private-address, redirect, credential, timeout,',
      'content-type, and size policy.',
      '',
      'Inbound fixed Bearer remains available. For dynamic production access tokens KodaX is',
      'an OAuth Resource Server: it validates external-issuer RFC 9068 JWTs and JWKS, but does',
      'not issue or sign tokens. Every authentication adapter supplies a stable `securityRealm`;',
      'task ownership hashes realm, subject, and tenant so authority changes fail closed.',
      'Pre-realm durable tasks stay inaccessible during normal serving. Stop the server, run',
      '`kodax a2a migrate-tasks` for a dry-run, then apply with --confirm-server-stopped;',
      'custom hosts use `migrateA2ALegacyTaskOwners()` with exact mappings. KodaX never',
      'guesses an owner or uses heuristic dual-read fallback.',
      '',
      'The built-in listener is loopback-only; public deployment wraps `handle()` in host-owned',
      'TLS and authorization. INPUT_REQUIRED resumes the original Runtime run. Task history and',
      'listing are bounded, terminal retention prunes oldest records, and pagination uses a',
      'stable opaque cursor. Only explicitly admitted artifacts are published: staged outputs,',
      'successful admitted Skill-script outputs, negotiated remote file Parts, or authorized URI',
      'references. Ordinary workspace writes, local paths, prompts, credentials, and raw tool',
      'traffic are never exposed implicitly.',
    ].join('\n'),
    sources: [
      { label: 'A2A SDK guide', path: 'docs/SDK_EMBEDDER_GUIDE.md' },
      { label: 'A2A client', path: 'src/a2a/client-executor.ts' },
      { label: 'A2A server', path: 'src/a2a/server.ts' },
      { label: 'A2A CLI', path: 'src/integration-cli.ts' },
    ],
    nextTopics: ['config', 'sdk', 'agents'],
  },
  {
    id: 'repo-intelligence',
    title: 'Repo intelligence',
    aliases: ['repointel', 'repo intel', 'code intelligence', '仓库智能', '代码库理解'],
    summary: 'What the repo-intelligence tools do and their limits.',
    body: [
      'Repo intelligence gives the agent a repo-scope map (overview, symbols, module/flow',
      'capsules, change-impact) to narrow scope before large reviews/refactors — cached under',
      '<repo>/.agent/repo-intelligence/. Modes via repoIntelligenceMode / KODAX_REPO_INTELLIGENCE',
      '(auto/off/light/full). It is batch, pre-task context — not a realtime type checker.',
    ].join('\n'),
    sources: [{ label: 'repo-intelligence', path: 'packages/coding/src/repo-intelligence/' }],
    nextTopics: ['tools', 'config', 'sessions'],
  },
  {
    id: 'sessions',
    title: 'Sessions & goals',
    aliases: ['session', 'resume', 'compaction', 'goal', '会话', '恢复', '目标'],
    summary: 'resume / -c / -r, compaction, per-project storage, /goal.',
    body: [
      'Continue work: `kodax -c` (most recent session) or `kodax -r` (pick one). Long sessions',
      'compact automatically to stay within context. Sessions are stored per project. Set a',
      'persistent objective with the /goal',
      'command; the agent tracks it and a verifier checks completion.',
      'If a provider starts rejecting the current history (oversized or locked session), /recover',
      'forks a fresh session seeded from a compact local summary instead of replaying raw history.',
      'Clean duplicate ghost sessions with `kodax sessions dedupe` (dry-run first; reversible archive).',
    ].join('\n'),
    sources: [{ label: 'session storage', path: 'packages/repl/src/interactive/storage.ts' }],
    nextTopics: ['memory', 'commands', 'troubleshooting'],
  },
  {
    id: 'memory',
    title: 'Governed memory',
    aliases: ['memory', 'remember', 'recall', 'memory agent', 'memory_recall', '记忆', '记住', '回忆'],
    summary: 'F228 memory governance, automatic recall, deliberate query, and the experimental SDK.',
    body: [
      'Top-level coding runs use the existing F228 Memory Control Plane. At session start KodaX',
      'builds an exact-scoped memory pack; passive recall stays on the zero-wait hot path. When',
      'the current context cannot answer a specific question about prior execution experience or',
      'a user preference, the Action LLM may call the read-only memory_recall tool. Current',
      'repository facts must still come from current tools, not memory.',
      '',
      'Recalled text is low-authority evidence, never an instruction override. Scope, secret',
      'filtering, source evidence, lifecycle, and mutation protection are deterministic code gates.',
      'Use /memory list|pending|show|approve|reject|curate|rebuild|open to inspect and govern the',
      'project memory plane. Durable changes still require proposal/preview/fingerprint/apply;',
      'KodaX does not expose filesystem memory actions or auto-edit prompts, policy, code, or weights.',
      '',
      'SDK hosts can opt into @kodax-ai/kodax/experimental-memory. MemorySession.recall() is',
      'synchronous; query() is deliberate and read-only; observe(), complete(), rewind(), and close()',
      'provide bounded episode lifecycle. Decision receipts are trace-only and do not store hidden',
      'reasoning. This subpath is experimental; the F228 control plane remains the only durable store.',
    ].join('\n'),
    sources: [
      { label: 'coding memory runtime', path: 'packages/coding/src/agent-runtime/run-substrate.ts' },
      { label: 'memory recall tool', path: 'packages/coding/src/tools/memory-recall.ts' },
      { label: 'memory command', path: 'packages/repl/src/commands/memory-command.ts' },
      { label: 'experimental memory SDK', path: 'packages/agent/src/experimental-memory/' },
    ],
    nextTopics: ['sessions', 'tools', 'sdk'],
  },
  {
    id: 'doctor',
    title: 'kodax doctor',
    aliases: ['doctor', 'diagnose', 'health check', 'ping', '诊断', '体检'],
    summary: 'Diagnose config/provider/credential issues; --ping live reachability.',
    body: [
      'Run `kodax doctor` to print a health report: configured provider(s), credential/config',
      'state, and storage directories. Add `kodax doctor --ping` to live-probe whether each',
      'configured provider is reachable with the current key. This is the first stop for',
      'connection / 401 / 429 / "provider not working" problems.',
    ].join('\n'),
    sources: [{ label: 'doctor CLI', path: 'src/kodax_doctor.ts' }],
    nextTopics: ['troubleshooting', 'providers', 'config'],
  },
  {
    id: 'sdk',
    title: 'SDK',
    aliases: ['embed', 'library', 'api', 'sdk入门', '嵌入'],
    summary: 'Published subpaths, shared Runtime hosting, packaged Electron, A2A, and memory.',
    body: [
      'The source monorepo has 4 workspace packages: @kodax-ai/llm, @kodax-ai/agent,',
      '@kodax-ai/coding, and @kodax-ai/repl. The published @kodax-ai/kodax bundle exposes',
      '11 SDK subpaths: /agent, /llm, /coding, /media, /repl, /skills, /mcp, /session,',
      '/runtime, /a2a, and /experimental-memory.',
      'Use @kodax-ai/kodax/coding for coding tasks; @kodax-ai/kodax/runtime for embedded,',
      'Worker-hosted, or local-daemon sessions/runs/events/permissions;',
      '@kodax-ai/kodax/a2a for the A2A 1.0 JSON-RPC/SSE client/server edge; and',
      '@kodax-ai/kodax/experimental-memory for the opt-in MemoryAgent/MemorySession contract.',
      'For an A2A server, listen() waits for durable recovery; a host wiring handle() directly',
      'can await server.whenReady() before accepting traffic.',
      'External Agent owner planes bound close to a 30-second default across admitted work',
      'and executor disposal; hosts may set a positive finite `closeTimeoutMs` override.',
      '',
      'The shared local daemon is authoritative for one Coder profile. Join a session atomically',
      'with sessions.observe(); replace local projection after runtime change/resync_required.',
      'Control mutations use durable operation identities and settings/permission revisions.',
      'AskUser and permissions are transport-safe. Provider credentials are requested just in',
      'time and scoped to a run/provider; run-bound Host Tools never leak into unrelated CLI',
      'runs. Daemon/inline ownership is fenced, and inline rollback remains sticky. Partner',
      'products keep their separate private embedded Runtime.',
      '',
      'Packaged/asar Electron hosts may use daemon auto-start when the default-enabled',
      'RunAsNode fuse is available. `homeDir` is the CLI-style base directory that owns',
      '`.kodax`; `KODAX_HOME` is the lower-level `.kodax` path. ELECTRON_RUN_AS_NODE exists',
      'only at the detached child exec boundary and is removed before daemon or user child',
      'code loads. If the fuse is disabled, start the daemon with ordinary Node/CLI and use',
      'attach-only mode; KodaX does not reopen the GUI or silently fall back to inline mode.',
      '',
      'The SDK is ESM-only. Capability queries such as per-model context/limits, credential',
      'verification, and agent discovery can support embedder UIs without starting a coding run.',
    ].join('\n'),
    sources: [
      { label: 'published exports', path: 'package.json' },
      { label: 'Runtime facade', path: 'src/sdk-runtime.ts' },
      { label: 'A2A facade', path: 'src/sdk-a2a.ts' },
      { label: 'SDK embedder guide', path: 'docs/SDK_EMBEDDER_GUIDE.md' },
    ],
    nextTopics: ['providers', 'agents', 'tools'],
  },
  {
    id: 'troubleshooting',
    title: 'Troubleshooting',
    aliases: ['error', 'problem', '401', '429', 'fix', '排障', '报错', '问题'],
    summary: 'First run kodax doctor; provider 401/429, network, Windows paths, Node/npm.',
    body: [
      'First: run `kodax doctor --ping` to localize the problem.',
      '- 401 / unauthorized: key missing/invalid — check provider env var or config.json.',
      '- 429 / rate limit: back off, or set KODAX_FALLBACK_PROVIDERS for cross-provider fallback.',
      '- Network: corporate proxy / region blocks can fail provider endpoints.',
      '- Windows: paths use forward slashes internally; case-insensitive workspace match is handled.',
      '- Node/npm: ensure Node >= 20; reinstall the global package if the CLI is stale.',
    ].join('\n'),
    sources: [{ label: 'doctor CLI', path: 'src/kodax_doctor.ts' }],
    nextTopics: ['doctor', 'providers', 'config'],
  },
];

export const MANUAL_REGISTRY: Readonly<Record<KodaXManualTopicId, KodaXManualTopic>> =
  Object.freeze(
    Object.fromEntries(TOPICS.map((t) => [t.id, t])) as Record<KodaXManualTopicId, KodaXManualTopic>,
  );

/** Exposed for drift-guard tests (providers topic must cover every provider). */
export const MANUAL_PROVIDER_NAMES = PROVIDER_NAMES;
