/**
 * KodaX - 极致轻量化 Coding Agent
 *
 * 根入口文件 - 代理到 monorepo packages
 */

// Core API - 从 @kodax-ai/coding 重新导出
export * from '@kodax-ai/coding';
export {
  ACP_LOG_LEVELS,
  AcpLogger,
  resolveAcpLogLevel,
  type AcpLogLevel,
} from './acp_logger.js';
export {
  AcpEventEmitter,
  type AcpEventSink,
  type AcpRuntimeEvent,
} from './acp_events.js';
export {
  createKodaXRuntime,
  acquireKodaXInlineOwner,
  connectKodaXRuntime,
  enableKodaXDaemonOwner,
  getKodaXRuntimeOwnerPolicy,
  getKodaXRuntimeOwnerState,
  parseRuntimeEvent,
  RuntimeTransportBoundaryError,
  setKodaXRuntimeOwnerMode,
} from './sdk-runtime.js';
export type {
  CreateKodaXRuntimeOptions,
  KodaXDaemonRuntime,
  KodaXRuntime,
  KodaXRuntimeMode,
  RuntimeInlineOwnerHandle,
  RuntimeOwnerPolicyState,
  RuntimeOwnerIdentity,
  RuntimeOwnerState,
  RuntimeCreateSessionInput,
  RuntimeEvent,
  RuntimeEventEnvelope,
  RuntimeEventParseResult,
  RuntimeEventPayloadMap,
  RuntimeEventFilter,
  RuntimeEventListener,
  RuntimeTypedEventListener,
  RuntimeEventReplayFilter,
  RuntimeEventService,
  RuntimeEventType,
  RuntimeTypedEvent,
  RuntimeTextDeltaEventPayload,
  RuntimeThinkingFinishedEventPayload,
  RuntimeToolStartedEventPayload,
  RuntimeToolProgressEventPayload,
  RuntimeToolFinishedEventPayload,
  RuntimeRunProgressEventPayload,
  RuntimeTodoUpdatedEventPayload,
  RuntimeInteractionResolvedEventPayload,
  RuntimeWarningEventPayload,
  RuntimeForkSessionInput,
  RuntimeIdentity,
  RuntimeConnectionService,
  RuntimeConnectionState,
  RuntimeDaemonPreflight,
  RuntimeDaemonManagementService,
  RuntimeDaemonManagementState,
  RuntimeDaemonRollbackInput,
  RuntimeDaemonRollbackResult,
  RuntimeDaemonContextOptions,
  RuntimeDaemonKodaXOptions,
  RuntimeDaemonRunService,
  RuntimeDaemonStartRunInput,
  RuntimeKodaXOptions,
  RuntimePermissionRequestInput,
  RuntimePermissionDecision,
  RuntimePermissionFilter,
  RuntimePermissionRequest,
  RuntimePermissionRisk,
  RuntimePermissionScope,
  RuntimePermissionService,
  RuntimeOperationReceipt,
  RuntimeOperationService,
  RuntimeRunFilter,
  RuntimeRunHandle,
  RuntimeRunMode,
  RuntimeRunPhase,
  RuntimeRunResult,
  RuntimeRunService,
  RuntimeRunStatus,
  RuntimeRunRequirements,
  RuntimeSession,
  RuntimeRunSessionLoadedEventPayload,
  RuntimeSessionLoadedEventPayload,
  RuntimeSessionSettingsUpdatedEventPayload,
  RuntimeUserInputRequestedEventPayload,
  RuntimeSessionFilter,
  RuntimeSessionService,
  RuntimeSessionSettings,
  RuntimeSessionSettingsPatch,
  RuntimeSessionObservationSnapshot,
  RuntimeSessionSummary,
  RuntimeStatusService,
  RuntimeStatusSnapshot,
  RuntimeCredentialLease,
  RuntimeCredentialService,
  RuntimeHostToolInvocationStatus,
  RuntimeHostToolLease,
  RuntimeHostToolService,
  RuntimeSubscription,
  RuntimeTextInput,
  RuntimeUserInputFilter,
  RuntimeUserInputKind,
  RuntimeUserInputRequest,
  RuntimeUserInputResolution,
  RuntimeUserInputService,
  RuntimeTranscript,
  RuntimeWorkflowFilter,
  RuntimeWorkflowListener,
  RuntimeWorkflowService,
  RuntimeWorkflowSnapshot,
  RuntimeWorkflowSummary,
} from './sdk-runtime.js';
// ACP server API - server `cwd` can pin the session-level executionCwd for prompts and tools.
export { KodaXAcpServer, runAcpServer, type KodaXAcpServerOptions } from './acp_server.js';

// AAMP async task worker API.
export {
  KodaXAampServer,
  runAampServer,
  type KodaXAampServerOptions,
} from './aamp_server.js';
export {
  AAMP_LOG_LEVELS,
  JsonlAampLogger,
  createDefaultAampLogger,
  resolveAampLogLevel,
  type AampLogLevel,
  type AampLogger,
} from './aamp_logger.js';
export { KodaXAampRuntime, type KodaXAampRuntimeOptions } from './aamp_runtime.js';
export { FileAampTaskStore } from './aamp_store.js';
export { AampSdkTransport } from './aamp_sdk_transport.js';
export type {
  AampDispatchEnvelope,
  AampTaskAck,
  AampTaskRecord,
  AampTaskResult,
  AampTaskStatus,
  AampTaskStore,
  AampTransport,
  AampWorkerInput,
} from './aamp_types.js';

// REPL API - 从 @kodax-ai/repl 重新导出
export {
  runInkInteractiveMode,
  type InkREPLOptions,
  runInteractiveMode,
  processSpecialSyntax,
  type RepLOptions,
  InteractiveContext,
  createInteractiveContext,
  touchContext,
  parseCommand,
  executeCommand,
  BUILTIN_COMMANDS,
  type Command,
  type CommandCallbacks,
  type CurrentConfig,
  getVersion,
  KODAX_VERSION,
  getProviderModel,
  getProviderList,
  isProviderConfigured,
  hydrateProcessEnvFromShell,
  loadConfig,
  prepareRuntimeConfig,
  registerConfiguredCustomProviders,
  saveConfig,
  getGitRoot,
  rateLimitedCall,
  KODAX_DIR,
  KODAX_SESSIONS_DIR,
  KODAX_CONFIG_FILE,
  FileSessionStorage,
} from '@kodax-ai/repl';

export type { KodaXAampConfig, KodaXAampProfileConfig } from '@kodax-ai/repl';
